name: Test Fetch File

on:
  workflow_dispatch:

jobs:
  test-fetch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Specify the Python version you need

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests  # Ensure requests is installed

      - name: Check network connectivity
        run: |
          ping -c 4 google.com
          ping -c 4 repositoriodeis.minsal.cl

      - name: Run test fetch script
        run: python scripts/test_fetch_file.py
